environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  pointycastle: ^3.3.0
  convert: ^3.0.1
  asn1lib: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.1.2
  build_test: ^2.1.0
